SNAPSHOT_METRIC_MAP = {
    "Země": "country",  
    "Číslo": "number",
    "Hráč": "player",
    "Prestiž K": "prestize",
    "Vojáků K": "soldiers",
    "Tanků K": "tanks",
    "Stíhaček K": "fighters",
    "Bunkrů K": "bunkers",
    "Mechů K": "mechs",
    "Agentů": "agents",
    "Operací": "operations",
    "Konv rak": "conventional_rackets",
    "Bio rak": "biocid_rackets",
    "Emp rak": "emp_rackets",
    "Nukl rak": "nuclear_rackets",
    "Zkuš arm K": "army_experiences",
    "Hodnost": "rank",
    "Zkuš věk K": "experiences_of_age",
    "Sesvačenost": "sanctity",
    "T hospod K": "economic_technology",
    "T RychSt K": "construction_speed",
    "T Obchod K": "business",
    "T HustZa K": "population_density",
    "T Zemědě K": "farming",
    "T Továrn K": "factory_automation",
    "T Energe K": "energetics",
    "T vojen K": "military_technology",
    "T SílaZb K": "force_of_arms",
    "T DomTrh K": "domestic_market_price",
    "T Rakety K": "rocket_development",
    "T Protir K": "missile_defense",
    "T Rozvěd K": "intelligence_force",
    "T Výzkum K": "space_exploration",
    "Obyvatel M": "population",
    "Peněz M": "money",
    "Jídla K": "food",
    "Energie K": "energy",
    "Spokoj": "satisfaction",
    "Na trhu": "stored_on_the_market",
    "+peněz K": "money_increase",
    "+jídla": "food increase",
    "+energie": "energy_increase",
    "+vojáků": "soldiers_increase",
    "+dílů jedn": "parts_of_units_increase",
    "+technologií": "technology_increase",
    "Rozloha K": "area",
    "Vesnice K": "villages",
    "Města K": "cities",  
    "Obchod z K": "business_zones",
    "Farmy K": "farms",
    "Laborato K": "laboratories",
    "Továrny K": "factories",
    "Kasárny K": "barracks",
    "Elektrár K": "power_plants",
    "Záb stř K": "entertainment_centers",
    "Voj zákl K": "vojenskych_zakladen",
    "Staveb fir": "military_bases",
    "Nezastav K": "unbuilt",
    "Ruiny K": "ruins",
    "B vesnice": "bonus_villages",
    "B farmy": "bonus_farms",
    "B laborat": "bonus_laboratories",
    "B továrny": "bonus_factories",
    "B kasárny": "bonus_barracks",
    "B elektrár": "bonus_power_plants",
    "B voj zákl": "bonus_military_bases",
    "B peníze": "bonus_money",
    "B max hosp": "bonus_max_economic_technolgies",
    "B max voj": "bonus_max_military_technologies",
    "B efekt hosp": "bonus_efekt_economy_technologies",
    "B útok": "bonus_attak",
    "B obrana": "bonus_defense",
    "B koloniz": "bonus_colonization",
    "B žoldy": "bonus_wages",
    "Logout": "logout",
    "Rozvoj zač": "start_of_developing",
    "Hosp pomoc": "last_economic_aid",
    "Dostal HP": "incoming_aids",
    "Poslal HP": "outcoming_aids",
    "Hum pomoc": "last_humanitarian_aids",
    "Ali Fórum": "alliance_last_message",
    "Do poklad": "to_cash_register",
    "Z poklad M": "from_cash_register",
    "Vesmír": "space_exploartion_increase",
    "Utop spok K": "points_of_utopia",
    "Android": "proportion of androids",
    "UFO": "UFO_chance",
    "Emb Hlas": "embargo_votes",
    "Odehr kola": "played_rounds",
    "Volná kola": "free_rounds",
    "Nepř kola": "inaccessible_rounds"    
}

METRIC_KEYS = list(SNAPSHOT_METRIC_MAP.keys())