SNAPSHOT_METRIC_MAP = {
    "země": "country_name",  
    "číslo": "country_number",
    "hráč": "player_name",
    "prestiž k": "country_prestige",
    "vojáků k": "soldiers",
    "tanků k": "tanks",
    "stíhaček k": "fighters",
    "bunkrů k": "bunkers",
    "mechů k": "mechs",
    "agentů": "agents",
    "operací": "operations",
    "konv rak": "conventional_rackets",
    "bio rak": "biocid_rackets",
    "emp rak": "emp_rackets",
    "nukl rak": "nuke_rackets",
    "zkuš arm k": "army_experiences",
    "hodnost": "rank",
    "zkuš věk k": "experiences_of_age",
    "sesvačenost": "sanctity",
    "t hospod k": "economic_technologies",
    "t rychst k": "construction_speed",
    "t obchod k": "business",
    "t hustza k": "population_density",
    "t zemědě k": "farming",
    "t továrn k": "factory_automation",
    "t energe k": "energetics",
    "t vojen k": "military_technologies",
    "t sílazb k": "force_of_arms",
    "t domtrh k": "domestic_market_price",
    "t rakety k": "rocket_development",
    "t protir k": "missile_defense",
    "t rozvěd k": "intelligence_force",
    "t výzkum k": "space_exploration",
    "obyvatel m": "population",
    "peněz m": "money",
    "jídla k": "food",
    "energie k": "energy",
    "spokoj": "satisfaction",
    "na trhu": "stored_on_the_market",
    "+peněz k": "money_increase",
    "+jídla": "food_increase",
    "+energie": "energy_increase",
    "+vojáků": "soldiers_increase",
    "+dílů jedn": "parts_of_units_increase",
    "+technologií": "technology_increase",
    "rozloha k": "country_area",
    "vesnice k": "villages",
    "města k": "cities",  
    "obchod z k": "business_zones",
    "farmy k": "farms",
    "laborato k": "laboratories",
    "továrny k": "factories",
    "kasárny k": "barracks",
    "elektrár k": "power_plants",
    "záb stř k": "entertainment_centers",
    "voj zákl k": "military_bases",
    "staveb fir": "construction_companies",
    "nezastav k": "unbuilt",
    "ruiny k": "ruins",
    "b vesnice": "bonus_villages",
    "b farmy": "bonus_farms",
    "b laborat": "bonus_laboratories",
    "b továrny": "bonus_factories",
    "b kasárny": "bonus_barracks",
    "b elektrár": "bonus_power_plants",
    "b voj zákl": "bonus_military_bases",
    "b peníze": "bonus_money",
    "b max hosp": "bonus_max_economic_technolgies",
    "b max voj": "bonus_max_military_technologies",
    "b efekt hosp": "bonus_efekt_economy_technologies",
    "b útok": "bonus_attak",
    "b obrana": "bonus_defense",
    "b koloniz": "bonus_colonization",
    "b žoldy": "bonus_wages",
    "logout": "logout",
    "rozvoj zač": "start_of_developing",
    "hosp pomoc": "last_economic_aid",
    "dostal hp": "incoming_aids",
    "poslal hp": "outcoming_aids",
    "hum pomoc": "last_humanitarian_aids",
    "ali fórum": "alliance_last_message",
    "do poklad": "to_cash_register",
    "z poklad m": "from_cash_register",
    "vesmír": "space_exploartion_increase",
    "utop spok k": "points_of_utopia",
    "android": "proportion_of_androids",
    "ufo": "ufo_chance",
    "emb hlas": "embargo_votes",
    "odehr kola": "played_rounds",
    "volná kola": "free_rounds",
    "nepř kola": "inaccessible_rounds"    
}

METRIC_KEYS = list(SNAPSHOT_METRIC_MAP.items())
